# Generated by Django 3.2.7 on 2023-08-22 17:47

from django.db import migrations, models
import message.models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=1000000, null=True, upload_to=message.models.file_to),
        ),
    ]
