# Generated by Django 3.2.7 on 2023-11-04 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 27, 20, 476679, tzinfo=utc), verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 14, 27, 20, 476679), verbose_name='start_date'),
        ),
    ]
