# Generated by Django 3.2.7 on 2024-03-27 14:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20231104_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 15, 59, 4, 69516, tzinfo=utc), verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 15, 59, 4, 69516), verbose_name='start_date'),
        ),
    ]
