# Generated by Django 3.2.7 on 2024-03-27 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20240327_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 16, 16, 50, 123188, tzinfo=utc), verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 16, 16, 50, 123188), verbose_name='start_date'),
        ),
    ]
