# Generated by Django 3.2.7 on 2022-12-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_post_reposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
