# Generated by Django 3.2.7 on 2023-01-23 00:51

import block.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='avatar',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=block.models.block_to),
        ),
        migrations.AlterField(
            model_name='block',
            name='cover',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=block.models.block_for),
        ),
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=block.models.link_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, max_length=100000, null=True, upload_to=block.models.post_to),
        ),
    ]
