# Generated by Django 3.2.7 on 2023-01-27 12:49

import block.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_auto_20230123_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ImageField(blank=True, max_length=100000, null=True, upload_to=block.models.post_to),
        ),
    ]
