# Generated by Django 3.2.7 on 2022-12-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('C', 'comment'), ('P', 'post'), ('RP', 'repost'), ('VP', 'vote_post'), ('VC', 'vote_comment'), ('F', 'follow'), ('UF', 'unfollow'), ('CT', 'chat')], max_length=20),
        ),
    ]
